//! Postil review engine. See README for the product doctrine.

pub(crate) mod adjudication;
pub(crate) mod api_key;
#[cfg(feature = "qualification-candidate")]
pub mod attribution;
pub(crate) mod brevity;
pub mod cli;
pub mod config;
pub(crate) mod credentials;
pub mod diff;
pub mod doctor;
pub(crate) mod durable_plan;
pub mod envelope;
pub mod filter;
pub mod forge;
pub mod hook;
pub mod llm;
pub mod local;
pub mod login;
pub(crate) mod machine_claim;
pub mod output;
pub mod plan;
pub mod prompt;
pub(crate) mod repository_search;
pub(crate) mod resolve;
pub mod respond;
pub mod review;
pub mod sarif;
